package my.edu.utar.utarit;

public class Constants {
    public static final String SUPABASE_API_KEY ="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvcWV3Y25qenlxaXpqcWVjbHl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwOTY4MTMsImV4cCI6MjA3MzY3MjgxM30.WqX_33DLnmeVb8WWe5BiAUOJYijD1FffN6epN2xxfhE";

}
